# Generated by Django 5.0.1 on 2024-03-15 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0002_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('pending_status', models.CharField(choices=[('PAYMENT_STATUS_PENDING', 'pending'), ('PAYMENT_STATUS_COMPLETED', 'completed'), ('PAYMENT_STATUS_CANCELLED', 'cancelled')], default='PAYMENT_STATUS_PENDING', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
