# Generated by Django 5.0.1 on 2024-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='pending_status',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'cancelled')], default='PAYMENT_STATUS_PENDING', max_length=100),
        ),
    ]
