# Generated by Django 5.0.1 on 2024-03-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0006_remove_orders_pending_status_orders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
