# Generated by Django 5.0.1 on 2024-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
