# Generated by Django 5.0.1 on 2024-02-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_added_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_added',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartt', to='cart.cart'),
        ),
    ]
