# Generated by Django 5.0.1 on 2024-02-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_added_cart'),
        ('products', '0007_reviewrating_name_alter_reviewrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_added',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productt', to='products.products'),
        ),
    ]
