# Generated by Django 5.0.1 on 2024-03-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_added_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartsecond',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
