# Generated by Django 5.0.1 on 2024-03-02 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cartsecond_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsecond',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
