# Generated by Django 5.0.1 on 2024-03-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_itemsecond_user'),
        ('products', '0012_variations_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_itemsecond',
            name='variations',
            field=models.ManyToManyField(related_name='variationsadded', to='products.variations_added'),
        ),
    ]
