# Generated by Django 5.0.1 on 2024-02-19 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_categories_options'),
        ('products', '0004_reviewrating_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.categories'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.products'),
        ),
        migrations.CreateModel(
            name='productdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craeted_date', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('product_gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productgallery')),
                ('variations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variations')),
            ],
        ),
    ]
