# Generated by Django 5.0.1 on 2024-02-19 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_categories_alter_reviewrating_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='variations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.variations'),
        ),
    ]
